<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#0f766e"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>CRM Camp Resident MUTU | Admin</title>
    <link rel="manifest" href="{{ asset('manifest.webmanifest') }}"><link rel="stylesheet" href="{{ asset('css/admin.css') }}">
</head>
<body>
<div id="loginPanel" class="auth-panel"><div class="auth-card"><div class="brand-mark">M</div><h1>CRM Camp Resident MUTU</h1><p class="muted">Masuk ke dashboard operasional</p><form id="adminLoginForm"><input id="loginEmail" type="email" placeholder="Email" required autocomplete="username"><input id="loginPassword" type="password" placeholder="Password" required autocomplete="current-password"><button class="btn primary" type="submit">Masuk</button><p id="loginError" class="error"></p></form></div></div>
<div id="dashboardApp" class="app-shell hidden"><aside class="sidebar"><div class="brand"><div class="brand-mark">M</div><div><strong>Camp Resident</strong><small>MUTU</small></div></div><nav class="nav"><a class="nav-item active" href="{{ route('admin.dashboard') }}">Dashboard</a><a class="nav-item" href="{{ route('admin.guests') }}">Tamu</a><a class="nav-item" href="{{ route('admin.rooms') }}">Kamar</a><a class="nav-item" href="{{ route('admin.bookings') }}">Booking</a><a class="nav-item" href="{{ route('admin.users') }}">User</a><a class="nav-item" href="/api/v1/reports/bookings?format=pdf">Laporan PDF</a></nav><div class="sidebar-card"><span class="chip success">Online</span><strong>Operasional Aktif</strong><p>Data ditampilkan langsung dari API Laravel.</p></div></aside>
<main class="main-panel"><header class="topbar"><div><p class="eyebrow">Overview</p><h1>Admin Dashboard</h1><p id="lastUpdated" class="muted">Memuat data...</p></div><div class="topbar-actions"><button class="btn secondary" id="themeToggle">Dark Mode</button><button class="btn secondary" id="installButton" hidden>Install PWA</button><button class="btn secondary" id="enablePushButton">Aktifkan Notifikasi</button><button class="btn danger" id="logoutButton">Keluar</button></div></header>
<section id="statsGrid" class="stats-grid"></section><section class="content-grid"><article class="panel panel-wide"><div class="panel-header"><h3>Aktivitas Booking</h3><button class="btn ghost" id="refreshButton">Refresh</button></div><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Tamu</th><th>Kamar</th><th>Check-in</th><th>Status</th></tr></thead><tbody id="bookingRows"><tr><td colspan="5">Memuat...</td></tr></tbody></table></div></article><article class="panel"><div class="panel-header"><h3>Ringkasan Operasional</h3></div><div id="operationalMetrics"></div></article></section>
<section class="bottom-grid"><article class="panel"><div class="panel-header"><h3>Booking Bulan Ini</h3><button class="btn ghost" id="calendarRefresh">Refresh</button></div><ul id="calendarEvents" class="notification-list"><li>Memuat kalender...</li></ul></article><article class="panel"><div class="panel-header"><h3>Quick Actions</h3></div><div class="quick-actions"><a class="btn primary" href="{{ route('admin.guests') }}">Kelola Tamu</a><a class="btn secondary" href="{{ route('admin.rooms') }}">Kelola Kamar</a><a class="btn secondary" href="{{ route('admin.bookings') }}">Kelola Booking</a></div><p id="toast" class="muted"></p></article></section></main></div>
<script src="{{ asset('js/admin.js') }}"></script></body></html>
